# Generated by Django 4.2.7 on 2026-08-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_sidebar_collapsed_organization_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('manager', 'Manager'), ('admin', 'Admin'), ('ceo', 'CEO'), ('support', 'Support'), ('org_support', 'Support')], max_length=20),
        ),
    ]
