# Generated by Django 4.2.7 on 2026-08-28 05:52
# QO'LDA TAHRIRLANDI: eski 'teacher'/'manager'/'org_support' rollariga ega
# BARCHA mavjud yozuvlarni "admin"ga ko'chiruvchi RunPython qadami qo'shildi
# (yangi hiyerarxiya: faqat support/ceo/admin/student qoladi). Bu qadam
# AlterField'dan OLDIN ishlaydi — avval ma'lumotlar to'g'rilanadi, keyin
# ROLE_CHOICES metama'lumoti tor(roq) qilinadi.

from django.db import migrations, models


def migrate_legacy_roles_to_admin(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    # 'org_support' — o'tgan (oraliq) bosqichda qo'shilgan, hech qachon
    # production'da ishlatilmagan bo'lishi ham mumkin, lekin xavfsizlik
    # uchun baribir hisobga olinadi. 'teacher'/'manager' — ilk arxitekturadan
    # qolgan eski rollar.
    User.objects.filter(role__in=['teacher', 'manager', 'org_support']).update(role='admin')


def reverse_noop(apps, schema_editor):
    # Orqaga qaytarib bo'lmaydi — qaysi yozuv aslida qaysi eski rolda
    # bo'lgani haqida ma'lumot saqlanmagan (barchasi "admin"ga birlashtirilgan).
    # Xavfsizlik uchun teskari migratsiya hech narsa qilmaydi.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_roles_to_admin, reverse_noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('ceo', 'CEO'), ('support', 'Support')], max_length=20),
        ),
    ]
