# Generated by Django 4.2.7 on 2026-08-19 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('academic', 'Academic'), ('general', 'General Training')], default='academic', max_length=20)),
                ('status', models.CharField(choices=[('on', 'Active'), ('off', 'Inactive')], default='on', max_length=10)),
                ('sections_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('current_section_index', models.IntegerField(default=0)),
                ('answers', models.JSONField(default=dict)),
                ('writing_text', models.JSONField(default=dict)),
                ('flagged', models.JSONField(default=dict)),
                ('notepad_text', models.TextField(blank=True)),
                ('font_level', models.IntegerField(default=1)),
                ('section_deadlines', models.JSONField(default=dict)),
                ('progress_data', models.JSONField(default=dict)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='accounts.user')),
            ],
            options={
                'db_table': 'exam_attempts',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='assigned_groups',
            field=models.ManyToManyField(to='exams.group'),
        ),
        migrations.AddField(
            model_name='exam',
            name='notif_seen_by',
            field=models.ManyToManyField(blank=True, related_name='exam_notifications', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='exam',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('file_url', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('file_mime', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(to='exams.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('target_students', models.ManyToManyField(blank=True, related_name='targeted_assignments', to='accounts.user')),
                ('viewed_by', models.ManyToManyField(blank=True, related_name='viewed_assignments', to='accounts.user')),
            ],
            options={
                'db_table': 'assignments',
            },
        ),
    ]
