# Generated by Django 4.2.7 on 2026-08-25 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_organization_sidebar_collapsed_organization_theme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sender_role', models.CharField(choices=[('support', 'Support'), ('ceo', 'CEO')], max_length=20)),
                ('sender_id', models.CharField(max_length=50)),
                ('sender_name', models.CharField(blank=True, max_length=150)),
                ('recipient_role', models.CharField(choices=[('ceo', 'CEO'), ('admin', 'Admin'), ('manager', 'Manager'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20)),
                ('recipient_id', models.CharField(max_length=50)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Yuborilgan'), ('read', "O'qilgan"), ('ignored', "E'tiborsiz qoldirilgan")], default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='accounts.organization')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_role', 'recipient_id', 'status'], name='messages_recipie_464269_idx'), models.Index(fields=['sender_role', 'sender_id'], name='messages_sender__f80bc8_idx')],
            },
        ),
    ]
