# Generated by Django 4.2.7 on 2026-08-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient_role',
            field=models.CharField(choices=[('ceo', 'CEO'), ('admin', 'Admin'), ('student', 'Student')], max_length=20),
        ),
    ]
