# Generated by Django 4.2.7 on 2026-09-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_message_recipient_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_role',
            field=models.CharField(choices=[('support', 'Support'), ('ceo', 'CEO'), ('admin', 'Admin')], max_length=20),
        ),
    ]
